### ISSUE TITLE
Other estimators than ML don't work

### ISSUE THREAD

**Issue by RobinAWester** [melissagwolf/dynamic#1]
Not sure whether this is an item for issues, but I just realized that cfaOne() does not work if the cfa-model was fitted using cfa(ordered = TRUE, estimator="WLSMV"). 
My solution was to just take the std. loadings from my model (estimated using WLSMV) and manually enter them. Do you know whether it leads to bias in the cutoffs if the simulation is based on ML?

**Comment by melissagwolf** [comment]
Good catch - this is only for ML estimation.  We do have a categorical approach in the pipeline, but it isn't available yet.  These cutoffs are not accurate for WLSMV estimation.  I'm glad you said something - I'll add a note to the documentation!  Thanks for pointing out that this isn't clear - I appreciate it.

**Comment by RobinAWester** [comment]
One of those questions I wish I hadn't asked for now I have to find another solution... Thanks for your quick response and the link to the paper!
