### ISSUE TITLE
catHB doesn't work

### ISSUE THREAD

**Issue by TomArriaza** [melissagwolf/dynamic#16]
I'm running a 3 factor solution for 25 categorical items (WLSMV estimator). I tried to get the dynamic fit index using the functions catHB, which I found here: https://rpubs.com/dmcneish/1025400, but the function is not part of the package according to R.

> dynamic::catHB(model1, plot=T)
Error: 'catHB' is not an exported object from 'namespace:dynamic'

**Comment by dmcneish18** [comment]
Are you using the CRAN or GitHub version of the package? The `cat` functions are not yet included in the CRAN package and are only accessible in the GitHub version of the package. 

This is mentioned in the "Installation" section of the README as well as the instructions for how to install the GitHub version of the package specifically (https://github.com/melissagwolf/dynamic?tab=readme-ov-file#installation)
