### ISSUE TITLE
DDDFI is not working 

### ISSUE THREAD

**Issue by SeWe-UniHi** [melissagwolf/dynamic#17]
Dear Melissa Wolf, 

I have analyzed several models about a month ago using dynamic:DDDFI(fit_one) and the code was working just finde. Now I wanted to replicate my analysis and am constantly getting this error: Error: 'DDDFI' is not an exported object from 'namespace:dynamic'

It would be great if you could provide some guidance regarding the problem. Thank you very much. 

Best, 
Selina

**Comment by dmcneish18** [comment]
Hi Selina, 

That warning indicates that function is not a part of the package. The DDDFI function is currently only available in the GitHub  version of the package, so is it possible that you are using the CRAN version of the package (e.g., perhaps you installed the CRAN version during the last month and it overwrote the GitHub package that contains the DDDFI function?)? When I checked the GitHub version, the DDDFI function is in the namespace and that error should not appear with the GitHub package.

Running `devtools::install_github("melissagwolf/dynamic", force=T)` should re-install the GitHub package and hopefully stop that error.

**Comment by SeWe-UniHi** [comment]
Hi Dan, 

thank you very much. Now it worked.
