### ISSUE TITLE
DDDFI Error

### ISSUE THREAD

**Issue by CD-Johnson-Mot** [melissagwolf/dynamic#20]
Hello Drs. Wolf and McNeish, 

I'm having an issue with the DDDFI function of the dynamic package where I receive the following error message when trying to generate DFIs for a 5-factor CFA: 

Error in DDDFI(model = T2_StModFit, data = T2_PMC_DFI, estimator = "MLR",  : 
  could not find function "DDDFI"

Here is the original code for both the model and the DDDFI function. Previously, this code successfully produced 3DFIs but now I cannot get past this error (even after reinstalling the package from github). I am still in the early stages of learning R, so I'm not sure if I'm missing something. Any support would be greatly appreciated!  

Original code: 

```{r}
library(lavaan)
T2_StMod <- 'T2_IMP =~ T2PImp1 + T2PImp2 + T2PImp3 + T2PImp4
T2_EFF =~ T2PEff1 + T2PEff2 + T2PEff3 + T2PEff4 + T2PEff5
T2_REL =~ T2PRel1 + T2PRel2 + T2PRel3
T2_CON =~ T2PCon1 + T2PCon2 + T2PCon3 + T2PCon4
T2_CMP =~ T2PCmp1 + T2PCmp2 + T2PCmp3 + T2PCmp4 + T2PCmp5'

T2_StModFit <- cfa(T2_StMod, data = T2_PMC_DFI, estimator = "MLR", mimic= "Mplus", missing = "FIML")
summary(T2_StModFit, fit.measures = TRUE, standardized = T)
```

# Generating DFIs for hypothesized model at T2 
```{r}
library(dynamic)
DDDFI(model = T2_StModFit, data = T2_PMC_DFI, estimator = "MLR", scale = "nonnormal")
```

**Comment by dmcneish18** [comment]
I think that warning indicates that function is not a part of the package. The DDDFI function is currently only available in the GitHub version of the package, so is it possible that you are using the CRAN version of the package (e.g., perhaps you installed the CRAN version when between the last time the code was run and now and it overwrote the GitHub package that contains the DDDFI function?)? When I checked the GitHub version, the DDDFI function is in the namespace and that error should not appear with the GitHub package installed.

Running devtools::install_github("melissagwolf/dynamic", force=T) should re-install the GitHub package and hopefully stop that error.

Alternatively, if getting packages into R correctly is causing some issues, the shiny version of the software (www.dynamicfit.app) can support your model with a point and click interface. The "Measurement Model" app (First option on the top row of the landing page) had Direct discrepancy DFI (DDDFI) as as option.

**Comment by CD-Johnson-Mot** [comment]
Hello Dr. McNeish, following up to let you know that I reinstalled the github package and the DDDFI function is working again for me. Thanks very much for your help with this issue, I'm really enjoying the package!

**Comment by CD-Johnson-Mot** [comment]
No problem at all, I'll be sure to keep an eye out for future updates here!
