### ISSUE TITLE
Error in multi factor CFA

### ISSUE THREAD

**Issue by tkasci** [melissagwolf/dynamic#4]
When trying the following:

```
library(dynamic)

sem.model <- "
NT =~ .57*x1 + .56*x2 + .47*x3 + .52*x4 + .39*x5
PT =~ .51*x6 + .83*x7 + .43*x8 + .32*x9
DM =~ .43*x10 + .68*x11 + .63*x12 + .66*x13 + .59*x14
AA =~ .53*x15 + .63*x16 + .47*x17 + .66*x18 + .69*x19
"

sem.sim <- dynamic::cfaHB(model = sem.model, n = 900, manual = T)

```

I get the following error:

`Error in x[[jj]][iseq] <- vjj : replacement has length zero`

One-factor models work fine, but I can't seem to get this to work.

**Comment by melissagwolf** [comment]
The package isn't set up to accommodate fully orthogonal multi-factor
models.  Did you mean to specify one?  Either way, I will update the code
so that it can run orthogonal models and let you know when it's resolved.
Thanks for pointing out the error.

**Comment by melissagwolf** [comment]
In the meantime, you can get the model to run by setting the factor correlations to 0 manually, e.g.:

sem.model <- "
NT =~ .57*x1 + .56*x2 + .47*x3 + .52*x4 + .39*x5
PT =~ .51*x6 + .83*x7 + .43*x8 + .32*x9
DM =~ .43*x10 + .68*x11 + .63*x12 + .66*x13 + .59*x14
AA =~ .53*x15 + .63*x16 + .47*x17 + .66*x18 + .69*x19
NT ~~ 0*PT + 0*DM + 0*AA
PT ~~ 0*DM + 0*AA
DM ~~ 0*AA
"

**Comment by melissagwolf** [comment]
You're missing the factor correlations in your model statement.  If you're running an orthogonal model, set the factor correlations to 0, e.g.:
```
sem.model <- "
NT =~ .57*x1 + .56*x2 + .47*x3 + .52*x4 + .39*x5
PT =~ .51*x6 + .83*x7 + .43*x8 + .32*x9
DM =~ .43*x10 + .68*x11 + .63*x12 + .66*x13 + .59*x14
AA =~ .53*x15 + .63*x16 + .47*x17 + .66*x18 + .69*x19
NT ~~ 0*PT + 0*DM + 0*AA
PT ~~ 0*DM + 0*AA
DM ~~ 0*AA
"
```
