### ISSUE TITLE
Add option to store results in a file and retrieve results from file

### ISSUE THREAD

**Issue by WillemSleegers** [melissagwolf/dynamic#6]
Since it can take a while to run the simulations, it might be nice to add an option to store the results in a file and retrieve the results from the file if the function is called again (for an example, see the `file` argument in the `brm()` function from the `brms` package).

**Comment by melissagwolf** [comment]
This is a great idea - thanks for the suggestion! I'll definitely look into this. We're also planning to add an option to print/pdf results for app users. Keep the good ideas coming!
