### ISSUE TITLE
dplyr deprecation warning message

### ISSUE THREAD

**Issue by WillemSleegers** [melissagwolf/dynamic#8]
I get the following warning message when I use the `dynamic` package:

```
Warning message:
Returning more (or less) than 1 row per `summarise()` group was deprecated in dplyr 1.1.0.
ℹ Please use `reframe()` instead.
ℹ When switching from `summarise()` to `reframe()`, remember that `reframe()` always
  returns an ungrouped data frame and adjust accordingly.
```

The new `dplyr` update has deprecated some functions so it looks like this package needs to be updated.

**Comment by melissagwolf** [comment]
Thanks for letting me know! Can you give me your model statement so that I can figure out where this is happening?

**Comment by WillemSleegers** [comment]
Pretty sure you see it anytime you run `cfaHB()` or `cfaOne()`. Running one of the examples from `cfaHB()` definitely shows it.

**Comment by sda030** [comment]
Hi @melissagwolf, I just installed the package (really neat idea and interface by the way). However, I still get this warning. Have you pushed your fix?
